packages:
  - apps/daemon
  - apps/web-inspector
  - apps/sheet
  - apps/bcl
  - apps/ui
  - packages/core
  - packages/std
  - packages/comm
  - packages/eth-rpc
  - packages/bassline-text-vscode
allowBuilds:
  esbuild: true
